### PR TITLE
Promote staging to master

### PR DESCRIPTION
**Pull request by mojavelinux**
Bring master up to date with staging as of 2016-08-11.

### CODE REVIEW

**Comment by mojavelinux** [comment]
Must be merged at the same time https://github.com/mulesoft/mulesoft-docs/pull/707 is merged.

**Comment by hsablonniere** [comment]
This is now handled in #31.

**Comment by mojavelinux** [comment]
I'm going to plan to merge this tonight.

**Comment by mojavelinux** [comment]
Correction, I plan to merge #31. This one should be withdrawn.

**Pull request closed without merging**
